# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0425aad785e7789c311adf0c2302d80d116de0586e7a520f83cd1cc85e7c19b2b56cfe5c12b1efc7b0f5b1ebf7d8c5179b6b6ad5de331919aaed4d7ab8df9eb6

test:
  secret_key_base: 856581672fe02103203f5dd20d7f3b92f88a7ef7ed32d3155020b2178873dacf999ce5d7c83cf7b2dea19a088f9d5a625e6771737117eddc058517ba4dfc4203

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
